name: hello-world
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'hello cloud engineers! Have an awesome day!' I cant wait to have a vacation
